// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_v2_alerts_index from "./routes/api/v2/alerts/index.ts";
import * as $api_v2_receivers from "./routes/api/v2/receivers.ts";
import * as $api_v2_status from "./routes/api/v2/status.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Timeline from "./islands/Timeline.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/v2/alerts/index.ts": $api_v2_alerts_index,
    "./routes/api/v2/receivers.ts": $api_v2_receivers,
    "./routes/api/v2/status.ts": $api_v2_status,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Timeline.tsx": $Timeline,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
